### ISSUE TITLE
undefined to_sym with hiera

### ISSUE THREAD

**Issue by liorclub** [justindowning/puppet-statsd#41]
I tried to install the module but I keep getting hiera errors:
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Error from DataBinding 'hiera' while looking up 'statsd::librato_skipInternalMetrics': undefined method `to_sym' for []:Array on node beadmin-dev0-lior-cm-3f4gxw0f.sizmek Warning: Not using cache on failed catalog Error: Could not retrieve catalog; skipping run

Can you please advice ?
	
puppet version: 3.8.7 Ruby version: 1.8.7 hiera version: 1.3.4 

stackoverflow: http://stackoverflow.com/questions/37115759/puppet-undefined-method-to-sym-for-array 

Thanks in advance

**Comment by justindowning** [comment]
According to your SO post, you're only using the Graphite backend, so you shouldn't even be setting Stackdriver or Librato params. My hunch is you have a bad config in your hierarchy for the `statsd::librato_skipInternalMetrics` key. Check in the files in your hierarchy for this:
```
:hierarchy:
  - client/%{clientcert}
  - roles/%{role}
  - environment/%{env}
  - global```
