### ISSUE TITLE
Use of camelcase for variables

### ISSUE THREAD

**Issue by mleklund** [justindowning/puppet-statsd#47]
According to the style guide, camelcase should not be used for variables:

https://docs.puppet.com/puppet/4.10/style_guide.html#variable-format

Where this bites us is use of PuppetSyntax, when setting `PuppetSyntax.check_hiera_keys = true` we get:

```
WARNING: hieradata/common.yaml: Key :statsd::flushInterval: Not a valid Puppet variable name for automatic lookup
WARNING: hieradata/common.yaml: Key :statsd::graphiteHost: Not a valid Puppet variable name for automatic lookup
WARNING: hieradata/common.yaml: Key :statsd::graphitePort: Not a valid Puppet variable name for automatic lookup
WARNING: hieradata/common.yaml: Key :statsd::deleteIdleStats: Not a valid Puppet variable name for automatic lookup
```

**Comment by justindowning** [comment]
I'd prefer to leave this as is to map directly with the key format used in statsd.

**Comment by mleklund** [comment]
It took the puppet syntax guys to get back to me:

https://github.com/voxpupuli/puppet-syntax/issues/79

https://docs.puppet.com/puppet/4.1/lang_reserved.html#parameters

The camelcase parameters are not acceptable by puppet 4 standards.
