### ISSUE TITLE
no systemd init system support

### ISSUE THREAD

**Issue by confiq** [justindowning/puppet-statsd#48]
it's in most Linux OS today. 
Unfortunately, it's not supported on this module.
Ubuntu/Debian does not have `upstart` anymore...

**Comment by confiq** [comment]
ooh now I see there is a PR #46 yet it's not in 3.0.0 ...

**Comment by justindowning** [comment]
Release 3.1.0 👉  https://forge.puppet.com/jdowning/statsd/3.1.0/readme

**Comment by Etherdaemon** [comment]
A big assumption - can we override this? Ubuntu trusty by default I get the following message:

Error: /Stage[main]/Statsd/Service[statsd]: Provider systemd is not functional on this host

When I flip back to 3.0.0 it's fine.
