### ISSUE TITLE
undefined method `to_json' for "./backends/repeater"

### ISSUE THREAD

**Issue by dongwenjuan** [justindowning/puppet-statsd#57]
Hi,
I followed the guide: https://forge.puppet.com/jdowning/statsd to install statsd server with repeater backend. But when I run `puppet agent -t` in the agent node, it raise the exception: 

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Failed to parse template statsd/localConfig.js.erb:
  Filepath: /etc/puppet/modules/statsd/templates/localConfig.js.erb
  Line: 4
  Detail: undefined method `to_json' for "./backends/repeater":String
 at /etc/puppet/modules/statsd/manifests/config.pp:81 on node common.oz
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

Some facts of my env:
operatingsystem => Ubuntu
operatingsystemrelease => 14.04
osfamily => Debian
puppetversion => 3.4.3
rubysitedir => /usr/local/lib/site_ruby/1.9.1
rubyversion => 1.9.3

I'm not familiar with Ruby, can you please help? Thanks~

**Comment by jdowning** [comment]
Hi @dongwenjuan. It looks like you are using a fairly old version of ruby (1.9.3). The json module got the `to_json` method added in [2.0.0](http://ruby-doc.org/stdlib-2.0.0/libdoc/json/rdoc/JSON.html#module-JSON-label-Generating+JSON). I recommend using a ruby version 2.0.0 or greater to correct this error.

**Comment by dongwenjuan** [comment]
Hi @jdowning, Thanks for your reply. I upgrade the puppet module stdlib from 4.10.0 to 4.25.1, and it resolved. Thanks~
