### ISSUE TITLE
Newrelic backend: exec vs nodejs::npm for install

### ISSUE THREAD

**Issue by kwstone14** [justindowning/puppet-statsd#58]
I'm in the middle of puppetizing installs of servers that run statsd, and I'm planning to use your module to facilitate that. I need to add support for a newrelic backend, and I was planning to make changes and submit a pull request once I confirm it's working. I see in backends.pp that exec is used to run the npm installs for the other supported backends. nodejs::npm could also be used for this. The README file recommends using puppet/nodejs to get node and npm installed on the server, but the exec resources suggest that you don't want to force a dependency on that package. Assuming you're interested in my adding newrelic backend support to the module, do you prefer that exec's be used?

**Comment by jdowning** [comment]
Hi! I am certainly interested in your PR to add NewRelic backend support. I prefer that you use the same patterns established with the other [backend](https://github.com/jdowning/puppet-statsd/blob/master/manifests/backends.pp) installations using `exec`. 

While this module is not forcing a dependency on how nodejs is installed, we do expect to invoke [npm](https://github.com/jdowning/puppet-statsd/blob/a317a9a89464ef87567e9932eb1b940e30882e45/manifests/params.pp#L6) to install the various backends.

**Comment by kwstone14** [comment]
I kind of thought that would be the case, but wanted to double-check. Will do with the use of exec.

Thanks!
Keith
